# Generated by Django 4.0.6 on 2022-07-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modelblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog')),
                ('name', models.CharField(max_length=150)),
                ('text', tinymce.models.HTMLField()),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='modelblogcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=150)),
                ('image', models.ImageField(upload_to='blogcategory')),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='modelcommentblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.modelblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modelblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.modelblogcategory'),
        ),
    ]
