# Generated by Django 4.0.6 on 2022-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusers',
            name='profileimage',
            field=models.ImageField(default='sdf', upload_to='profiles'),
            preserve_default=False,
        ),
    ]
