# Generated by Django 4.0.6 on 2022-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_modelusers_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusers',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
