# Generated by Django 4.0.6 on 2022-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modelusers_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusers',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
