# Generated by Django 4.0.6 on 2022-07-28 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_modelusers_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='modeltimedoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('longtime', models.DateTimeField()),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docter', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
