# Generated by Django 4.0.6 on 2022-07-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_modeltimedoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltimedoctor',
            name='longtime',
            field=models.TimeField(),
        ),
    ]
