# Generated by Django 4.0.6 on 2022-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_modeltimedoctor_longtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltimedoctor',
            name='endtime',
            field=models.TextField(),
        ),
    ]
