# Generated by Django 4.0.6 on 2022-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_modeltimedoctor_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltimedoctor',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modeltimedoctor',
            name='longtime',
            field=models.TextField(),
        ),
    ]
